/**
 * Generates src/environments/environment.ts from environment variables.
 * Run before every production build: `node scripts/set-env.mjs`
 * Set these variables in your Vercel project settings (or a local .env file).
 */

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { existsSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Load a local .env file if present (for local use without environment.development.ts)
const envFilePath = resolve(__dirname, '../.env');
if (existsSync(envFilePath)) {
  const raw = (await import('fs')).readFileSync(envFilePath, 'utf-8');
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const val = trimmed.slice(eq + 1).trim().replace(/^['"]|['"]$/g, '');
    if (!(key in process.env)) process.env[key] = val;
  }
}

function require_env(name) {
  const val = process.env[name];
  if (!val) {
    console.warn(`⚠️  ${name} is not set — using empty string`);
    return '';
  }
  return val;
}

const isProduction = process.env['NODE_ENV'] === 'production';

const env = {
  production: isProduction,
  firebase: {
    apiKey:            require_env('FIREBASE_API_KEY'),
    authDomain:        require_env('FIREBASE_AUTH_DOMAIN'),
    projectId:         require_env('FIREBASE_PROJECT_ID'),
    storageBucket:     require_env('FIREBASE_STORAGE_BUCKET'),
    messagingSenderId: require_env('FIREBASE_MESSAGING_SENDER_ID'),
    appId:             require_env('FIREBASE_APP_ID'),
    measurementId:     process.env['FIREBASE_MEASUREMENT_ID'] ?? '',
    databaseURL:       process.env['FIREBASE_DATABASE_URL'] ?? '',
  },
  googleMapsApiKey: '',
  amadeus: {
    clientId:     process.env['AMADEUS_CLIENT_ID'] ?? '',
    clientSecret: process.env['AMADEUS_CLIENT_SECRET'] ?? '',
    baseUrl:      process.env['AMADEUS_BASE_URL'] ?? (isProduction ? 'https://api.amadeus.com' : 'https://test.api.amadeus.com'),
  },
};

const content = `// Auto-generated by scripts/set-env.mjs — do not edit manually
export const environment = ${JSON.stringify(env, null, 2)};
`;

const outputPath = resolve(__dirname, '../src/environments/environment.ts');
writeFileSync(outputPath, content, 'utf-8');
console.log('✅  environment.ts generated');
